arm2:
  left_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint1
    pid: {p: 100.0, i: 0.01, d: 1.0}
  left_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint2
    pid: {p: 100.0, i: 0.01, d: 1.0}
  left_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint3
    pid: {p: 100.0, i: 0.01, d: 1.0}
  left_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint4
    pid: {p: 100.0, i: 0.01, d: 1.0}
  left_joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint5
    pid: {p: 100.0, i: 0.01, d: 1.0}
  left_joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint6
    pid: {p: 100.0, i: 0.0, d: 0.0}
  left_gripper_controller:
    type: effort_controllers/JointPositionController
    joint: left_finger_joint1 
#    pid: {p: 5.0, d: 1.0, i: 0.01}
    pid: {p: 5.0, i: 0.0, d: 0.0}

  right_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint1
    pid: {p: 100.0, i: 0.01, d: 1.0}
  right_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint2
    pid: {p: 100.0, i: 0.01, d: 1.0}
  right_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint3
    pid: {p: 100.0, i: 0.01, d: 1.0}
  right_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint4
    pid: {p: 100.0, i: 0.01, d: 1.0}
  right_joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint5
    pid: {p: 100.0, i: 0.01, d: 1.0}
  right_joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint6
    pid: {p: 100.0, i: 0.0, d: 0.0}
  right_gripper_controller:
    type: effort_controllers/JointPositionController
    joint: right_finger_joint1 
#    pid: {p: 5.0, d: 1.0, i: 0.01}
    pid: {p: 5.0, i: 0.01, d: 1.0}



