# Note: You MUST load these PID parameters for all joints that are using the
# PositionJointInterface, otherwise the arm + gripper will act like a giant
# parachute, counteracting gravity, and causing some of the wheels to lose
# contact with the ground, so the robot won't be able to properly navigate. See
# https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612
gazebo_ros_control:
  pid_gains:
    # these gains are used by the gazebo_ros_control plugin
    left_joint1:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    left_joint2:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    left_joint3:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    left_joint4:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    left_joint5:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    left_joint6:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    left_finger_joint1:
      p: 50.0
      i: 0.01
      d: 1.0
      i_clamp: 1.0
      antiwindup: false
      publish_state: true


    right_joint1:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    right_joint2:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    right_joint3:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    right_joint4:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    right_joint5:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    right_joint6:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    right_finger_joint1:
      p: 50.0
      i: 0.01
      d: 1.0
      i_clamp: 1.0
      antiwindup: false
      publish_state: true
