marm:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        left_joint1: {trajectory: 0.1, goal: 0.1}
        left_joint2: {trajectory: 0.1, goal: 0.1}
        left_joint3: {trajectory: 0.1, goal: 0.1}
        left_joint4: {trajectory: 0.1, goal: 0.1}
        left_joint5: {trajectory: 0.1, goal: 0.1}
        left_joint6: {trajectory: 0.1, goal: 0.1}
        right_joint1: {trajectory: 0.1, goal: 0.1}
        right_joint2: {trajectory: 0.1, goal: 0.1}
        right_joint3: {trajectory: 0.1, goal: 0.1}
        right_joint4: {trajectory: 0.1, goal: 0.1}
        right_joint5: {trajectory: 0.1, goal: 0.1}
        right_joint6: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - left_finger_joint1 
      - right_finger_joint1
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        left_finger_joint1: {trajectory: 0.1, goal: 0.1}
        right_finger_joint1: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
