marm:
  left_joint1_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint1
    pid: {p: 100.0, i: 0.01, d: 10}
  left_joint2_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint2
    pid: {p: 100.0, i: 0.01, d: 10}
  left_joint3_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint3
    pid: {p: 100.0, i: 0.01, d: 10}
  left_joint4_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint4
    pid: {p: 100.0, i: 0.01, d: 10}
  left_joint5_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint5
    pid: {p: 100.0, i: 0.01, d: 10}
  left_joint6_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint6
    pid: {p: 100.0, i: 0.01, d: 10}
  left_gripper_controller:
    type: effort_controllers/JointPositionController
    joint: left_finger_joint1 
    pid: {p: 5.0, d: 1.0, i: 0.01}

  right_joint1_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint1
    pid: {p: 100.0, i: 0.01, d: 10}
  right_joint2_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint2
    pid: {p: 100.0, i: 0.01, d: 10}
  right_joint3_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint3
    pid: {p: 100.0, i: 0.01, d: 10}
  right_joint4_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint4
    pid: {p: 100.0, i: 0.01, d: 10}
  right_joint5_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint5
    pid: {p: 100.0, i: 0.01, d: 10}
  right_joint6_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint6
    pid: {p: 100.0, i: 0.01, d: 10}
  right_gripper_controller:
    type: effort_controllers/JointPositionController
    joint: right_finger_joint1 
    pid: {p: 5.0, d: 1.0, i: 0.01}
